### ISSUE TITLE
Acme::* is a popular namespace people use for these for-testing-only distributions

### ISSUE THREAD

**Issue by perlancar** [skaji/CPAN-Test-Dummy-Perl5-DevRelease#1]
I personally use Acme::PERLANCAR::Test::*.

**Comment by skaji** [comment]
I guess CPAN-Test-Dummy-Perl5-\* is also a popular namespace to test cpan clients.
https://metacpan.org/search?q=CPAN-Test-Dummy-Perl5&search_type=modules

**Comment by perlancar** [comment]
Didn't know that. Cool :)

**Comment by skaji** [comment]
Now I can easily test dev releases :)
https://github.com/skaji/cpm/blob/wip/xt/20_dev.t
